name: ci

on:
  push:
    # Does not run on a tag push
    branches:
      - "*"
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.21.0]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -o app ./cmd
      - name: Test
        run: go test -v ./cmd -race -coverprofile=coverage.txt -covermode=atomic

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
